settings:
    ado_env:
      # Azure DevOps
      organization: organization-name
      application_url: https://dev.azure.com/
      issue_type_map: { Bug: Bug, Story: "User Story", Task: Task, Epic: Epic }
      status_map:
        {
          Draft: New,
          "In Progress": Active,
          Reopened: Active,
          "Customer Requirement/Draft": Draft,
          "Functional Requirement/Draft": Draft,
          "Test Case/New": Design,
          "To Do": New,
          "Done": Closed,
        }
      link_type_map:
        {
          "relates to": "System.LinkTypes.Related",

          "derives to": "System.LinkTypes.Dependency-Reverse",
          "derives from": "System.LinkTypes.Dependency-Forward",
          
          "trace to": "System.LinkTypes.Dependency-Reverse",
          "trace from": "System.LinkTypes.Dependency-Forward",

          "is tested by": "Microsoft.VSTS.Common.TestedBy-Forward",
          "tests": "Microsoft.VSTS.Common.TestedBy-Reverse",
        }

    data_center_env:
      # Data Center
      application_url: https://www.mywebsite.com/jira/
      username: data-center-username
      password: data-center-password
      # pat: data-center-personal-access-toke